ENH: Added 3D Elliptic Fourier Analysis
ALive-research/Slicer-Liver pull request #199
Opened 2023-02-01 01:17 UTC by dalbenzioG

At this stage, when sliding the MarkupDistanceContour a model node of the uniform sampled contour points will be generated.

2023-02-02 14:58 UTC, olevs requested changes

2023-02-02 14:58 UTC, olevs commented on Liver/Liver.py
> +    """Uses ScriptedLoadableModule base class, available at:
Change the indentation back to 2 spaces for now

2023-02-08 09:06 UTC, olevs commented
@dalbenzioG: Can you fix the indentation in Liver.py so we can merge your pull request?

2023-02-08 09:56 UTC, dalbenzioG commented
> @dalbenzioG: Can you fix the indentation in Liver.py so we can merge your pull request?
It shoud be fixed now. Sorry, my bad. My Pycharm IDE refactors back to 4 spaces indentation after I modified the Liver.py file.

2023-02-08 10:29 UTC, olevs approved these changes
A lot the the Python code could probably be converted to C++. Also some long functions (like runSurfacefromEFD) could be improved by splitting them into smaller functions.
Still, let's merge this now and possibly rewrite the code later

2023-02-08 10:32 UTC, olevs commented
> > @dalbenzioG: Can you fix the indentation in Liver.py so we can merge your pull request?
> > It shoud be fixed now. Sorry, my bad. My Pycharm IDE refactors back to 4 spaces indentation after I modified the Liver.py file.

We can change to 4 spaces if we want in a separate pull request after all other pull requests have been merged

2023-02-08 11:14 UTC, merged